package localhost._12306.hello_world_soap_http;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-11-07T11:10:56.472+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://localhost:12306/hello_world_soap_http", name = "Greeter")
@XmlSeeAlso({localhost._12306.hello_world_soap_http.types.ObjectFactory.class})
public interface Greeter {

    @WebResult(name = "responseType", targetNamespace = "http://localhost:12306/hello_world_soap_http/types")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.SayHiResponse")
    public String sayHi();

    @Oneway
    @RequestWrapper(localName = "greetMeOneWay", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.GreetMeOneWay")
    @WebMethod
    public void greetMeOneWay(
            @WebParam(name = "requestType", targetNamespace = "http://localhost:12306/hello_world_soap_http/types")
            String requestType
    );

    @WebResult(name = "responseType", targetNamespace = "http://localhost:12306/hello_world_soap_http/types")
    @RequestWrapper(localName = "greetMe", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.GreetMe")
    @WebMethod
    @ResponseWrapper(localName = "greetMeResponse", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.GreetMeResponse")
    public String greetMe(
            @WebParam(name = "requestType", targetNamespace = "http://localhost:12306/hello_world_soap_http/types")
            String requestType
    );

    @RequestWrapper(localName = "pingMe", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.PingMe")
    @WebMethod
    @ResponseWrapper(localName = "pingMeResponse", targetNamespace = "http://localhost:12306/hello_world_soap_http/types", className = "localhost._12306.hello_world_soap_http.types.PingMeResponse")
    public void pingMe() throws PingMeFault;
}
