
package localhost._12306.hello_world_soap_http;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2013-11-07T11:10:56.465+08:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "faultDetail", targetNamespace = "http://localhost:12306/hello_world_soap_http/types")
public class PingMeFault extends Exception {
    
    private localhost._12306.hello_world_soap_http.types.FaultDetail faultDetail;

    public PingMeFault() {
        super();
    }
    
    public PingMeFault(String message) {
        super(message);
    }
    
    public PingMeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PingMeFault(String message, localhost._12306.hello_world_soap_http.types.FaultDetail faultDetail) {
        super(message);
        this.faultDetail = faultDetail;
    }

    public PingMeFault(String message, localhost._12306.hello_world_soap_http.types.FaultDetail faultDetail, Throwable cause) {
        super(message, cause);
        this.faultDetail = faultDetail;
    }

    public localhost._12306.hello_world_soap_http.types.FaultDetail getFaultInfo() {
        return this.faultDetail;
    }
}
